// Curated snapshot: September 5, 2026. See README for maintenance notes.
const tournaments = [
  {id:'apa', name:'APA Austin Open', venue:'Austin Pickle Ranch', city:'North Austin', date:'2026-09-19', end:'2026-09-20', dateLabel:'September 19–20, 2026', day:'19–20', month:'SEP', drive:25, driveLabel:'25–35 min', price:75, priceLabel:'$65–75', dupr:true, rating:false, mixed:true, surface:'Indoor',
    url:'https://apatournaments.com/product/the-austin-open-austin-pickle-ranch/',
    summary:'A full weekend of indoor play, with a six-game guarantee.',
    divisions:'Men’s 3.5 on Saturday; mixed 3.5 on Sunday. Registration groups players by skill first, then age where participation allows.',
    format:'Round robin followed by brackets; six games guaranteed.',
    ratings:'Skill-based divisions. Age groups depend on participation; confirm the final grouping when registering.',
    reporting:'The organizer advertises that scores automatically post to DUPR.',
    cost:'The event directory lists $75; the individual event page still lists $65 early bird. A second event is $45 extra. Confirm the checkout price.',
    deadline:'September 15, under the organizer’s Tuesday-before-event policy.',
    note:'Price discrepancy: the directory and individual event page do not agree.',
    deadlineDate:'2026-09-15', deadlineLabel:'Register by Sep 15'},
  {id:'liveball', name:'Liveball @ PickleTex', venue:'PickleTex', city:'Georgetown', date:'2026-09-26', end:'2026-09-27', dateLabel:'September 26–27, 2026', day:'26–27', month:'SEP', drive:25, driveLabel:'25–35 min', price:42, priceLabel:'$42', dupr:true, rating:false, mixed:false, surface:'Covered outdoor',
    url:'https://app.fluidpb.com/tournaments/liveball-pickletex',
    summary:'Covered courts and guaranteed games, with a wider 3.5 rating range.',
    divisions:'Men’s 3.5 confirmed for Saturday. Mixed doubles is Sunday; the specific all-age mixed 3.5 bracket remains unverified.',
    format:'Guaranteed four games to 15 or five games to 11.',
    ratings:'Men’s 3.5: combined DUPR 6.25–8.05, with neither player above 4.03. This can be stronger than a strict combined-7.0 bracket.',
    reporting:'All divisions explicitly DUPR-recorded.',
    cost:'The men’s division lists $42. Price increases after September 8 and September 19.',
    deadline:'September 24, 2026.', note:'Confirm the all-age mixed 3.5 bracket. Men’s 3.5 permits a combined rating as high as 8.05.',
    deadlineDate:'2026-09-24', deadlineLabel:'Register by Sep 24'},
  {id:'nuron', name:'Nuron 1st Anniversary Tournament', venue:'The Picklr Austin Oak Hill', city:'Southwest Austin', date:'2026-09-26', end:'2026-09-26', dateLabel:'September 26, 2026', day:'26', month:'SEP', drive:40, driveLabel:'40–50 min', price:60, priceLabel:'$60–70', dupr:false, rating:true, mixed:true, surface:'Indoor',
    url:'https://app.fluidpb.com/tournaments/nuron-1st-anniversary-tournament',
    summary:'A close rating fit for both men’s and mixed, at the edge of the drive range.',
    divisions:'Men’s 3.5 in the morning; mixed 3.5 in the afternoon.',
    format:'Round robin followed by single-elimination playoffs; four games guaranteed.',
    ratings:'Both 3.5 brackets: combined DUPR 6.10–7.10, with neither player above 3.75.',
    reporting:'Result reporting is not stated. Ask the organizer before registering if DUPR reporting is essential.',
    cost:'Registration panel: $60 through September 9, then $70. An additional bracket costs $35.',
    deadline:'The registration panel shows September 24. Descriptive text instead says October 1 and gives September 15 for early bird; confirm with the organizer.',
    note:'Conflicting registration dates in the listing. The 40–50 minute drive is borderline for the preferred range.',
    email:'nuronpb@gmail.com', deadlineDate:'2026-09-24', deadlineLabel:'Sep 24 · confirm date'},
  {id:'tejas', name:'Everything Pickleball September Classic', venue:'Tejas', city:'Georgetown', date:'2026-09-27', end:'2026-09-27', dateLabel:'September 27, 2026', day:'27', month:'SEP', drive:30, driveLabel:'30–40 min', price:49, priceLabel:'$49', dupr:false, rating:true, mixed:false, surface:'Check venue details',
    url:'https://app.fluidpb.com/tournaments/everything-pickleball-september-classic',
    summary:'The closest men’s rating match: a strict combined DUPR cap of 7.0.',
    divisions:'Men’s doubles at noon. The all-age mixed division caps combined DUPR at 6.0, so the men’s bracket is the relevant option here.',
    format:'Five games guaranteed; the top four teams advance.',
    ratings:'Men’s: combined DUPR no higher than 7.0; neither player above 3.8. Eligibility uses ratings at registration, so a later increase does not disqualify you.',
    reporting:'Result reporting is not stated. Confirm directly with the organizer.',
    cost:'$49 for the relevant men’s bracket.', deadline:'September 24, 2026.',
    note:'Great rating fit, pending confirmation that results will be reported to DUPR.',
    email:'mrpickleballrick@aol.com', deadlineDate:'2026-09-24', deadlineLabel:'Register by Sep 24'},
  {id:'sun-city', name:'Sun City Fall Brawl', venue:'Sun City · North Courts', city:'Georgetown', date:'2026-10-03', end:'2026-10-04', dateLabel:'October 3–4, 2026', day:'03–04', month:'OCT', drive:30, driveLabel:'30–40 min', price:30, priceLabel:'$30', dupr:true, rating:false, mixed:true, surface:'North Courts',
    url:'https://swishtournaments.com/product/sun-city-fall-brawl/',
    summary:'An affordable weekend option, with open questions about eligibility.',
    divisions:'Men’s 3.5+ Saturday; mixed 3.5+ Sunday. North Courts, 700 County Road 245.',
    format:'Set-partner round robin followed by a medal bracket (single elimination).',
    ratings:'3.5+ is uncapped in the supplied listing. Confirm how strong the field will be.',
    reporting:'The registration page explicitly labels the event “DUPR Submitted.”',
    cost:'$30 per player for the first division, plus $20 for a second. The organizer requires registration and payment as a team.',
    deadline:'September 30, 2026.', note:'Confirm whether nonresidents may enter, and the expected level of the uncapped 3.5+ division.',
    deadlineDate:'2026-09-30', deadlineLabel:'Register by Sep 30'},
  {id:'apex', name:'002 Dink and Slam Pickleball Jam', venue:'Apex Pickleball Club', city:'Cedar Park', date:'2026-10-24', end:'2026-10-25', dateLabel:'October 24–25, 2026', day:'24–25', month:'OCT', drive:10, driveLabel:'10–15 min', price:65, priceLabel:'$65', dupr:true, rating:false, mixed:true, surface:'501 Cypress Creek Road',
    url:'https://app.fluidpb.com/tournaments/002DSPJ5',
    summary:'The closest major option, with every division reporting to DUPR.',
    divisions:'Men’s 3.5 Saturday; mixed 3.5 Sunday. Hosted at Apex on Cypress Creek Road.',
    format:'The relevant divisions use round robin followed by single-elimination playoffs.',
    ratings:'Men’s 3.5 permits individual ratings up to 4.04. It is not a strict combined-7.0 event.',
    reporting:'Every division is explicitly DUPR-recorded.',
    cost:'$65 for the first event, plus $30 for a second.', deadline:'Registration closes October 19; the refund cutoff is much earlier, September 15.',
    note:'Refund cutoff: September 15, well before the October event. Men’s 3.5 allows individual ratings up to 4.04.',
    deadlineDate:'2026-10-19', deadlineLabel:'Register by Oct 19'}
];

const leads = [
  {name:'Texas Ranchers Fall Round Up', venue:'The Picklr Round Rock', date:'September 12–13, 2026', tag:'TEAM EVENT · AVAILABILITY UNCONFIRMED', url:'https://app.fluidpb.com/', linkLabel:'Fluid PB event directory',
   text:'The relevant DUPR-14 division is listed for September 12 at 8 a.m. Four-player cap: 14.9. Matches include men’s, women’s, and mixed doubles. $75 per player. The supplied research showed the all-age DUPR-14 bracket as full; the event is no longer visible in the live directory checked September 5. Confirm event status, venue, availability, and DUPR reporting with the organizer.'},
  {name:'Saturday Showdown', venue:'Pickleball Kingdom · Pflugerville', date:'September 12, 2026 · confirm listing', tag:'MIXED DOUBLES · NEEDS CONFIRMATION', url:'https://pickleballkingdom.com/clubs/pflugerville/', linkLabel:'Club website',
   text:'The supplied club announcement advertises an intermediate mixed doubles tournament. Exact rating limits, entry fee, and DUPR reporting still need confirmation. The September announcement could not be recovered; this link goes to the club website, not a specific registration page.'},
  {name:'Brushy Creek MUD Pickleball Tournament', venue:'Brushy Creek Community Center · Round Rock', date:'September 12, 2026', tag:'YEAR CONFIRMED · BRACKET DETAILS TO CHECK', url:'https://www.bcmud.org/specialevents', linkLabel:'Official event calendar',
   text:'The official calendar now confirms September 12, 2026. The supplied event details list recreational and competitive men’s and mixed divisions, open to nonmembers, with a September 10 deadline. Reconfirm those division and registration details for 2026. Numerical rating limits and DUPR reporting remain unconfirmed.'},
  {name:'JOMG Pickleball Club Championship', venue:'Apex · Cedar Park', date:'September 19, 2026 · advertised adult divisions', tag:'CLUB TEAM EVENT · NEEDS CONFIRMATION', url:'https://pcc.jomgpickleball.com/', linkLabel:'Championship website',
   text:'Club-versus-club competition. Apex’s announcement says adult divisions return September 19. Ask your club about its DUPR-14 lineup, available places, and result reporting. The organizer’s website did not expose enough detail to reverify those points. This requires a club team, rather than only a doubles partner.'}
];
