// Curated snapshot: September 7, 2026. See README for maintenance notes.
const tournaments = [
  {men:true, women:true, mixedDetails:"Mixed 3.5: Sunday, September 20. Skill first, then age where participation permits.", womenDetails:"Women’s doubles: Saturday under APA’s standard doubles schedule. Select 3.5 at registration; confirm the final women’s bracket and age grouping.", menDetails:"Men’s 3.5: Saturday, September 19. Skill groups are split by age where entries allow.", id:'apa', name:'APA Austin Open', venue:'Austin Pickle Ranch', city:'North Austin', date:'2026-09-19', end:'2026-09-20', dateLabel:'September 19–20, 2026', day:'19–20', month:'SEP', drive:25, driveLabel:'25–35 min', price:75, priceLabel:'$65–75', dupr:true, rating:false, mixed:true, surface:'Indoor',
    url:'https://apatournaments.com/product/the-austin-open-austin-pickle-ranch/',
    summary:'A full weekend of indoor play, with a six-game guarantee.',
    divisions:'Men’s 3.5 on Saturday; mixed 3.5 on Sunday. Registration groups players by skill first, then age where participation allows.',
    format:'Round robin followed by brackets; six games guaranteed.',
    ratings:'Skill-based divisions. Age groups depend on participation; confirm the final grouping when registering.',
    reporting:'The organizer advertises that scores automatically post to DUPR.',
    cost:'The event directory lists $75; the individual event page still lists $65 early bird. A second event is $45 extra. Confirm the checkout price.',
    deadline:'September 15, under the organizer’s Tuesday-before-event policy.',
    note:'Price discrepancy: the directory and individual event page do not agree.',
    deadlineDate:'2026-09-15', deadlineLabel:'Register by Sep 15'},
  {men:true, women:true, mixedDetails:"Mixed 3.5: Sunday, September 27; all-age and 45+ brackets confirmed. Individual range 2.00–4.03; no combined cap displayed. Listed fee $42.", womenDetails:"Women’s 3.5: Saturday, September 26; all-age and 45+ brackets. Individual range 2.00–4.03; no combined cap displayed. Listed fee $43.", menDetails:"Men’s 3.5: Saturday, September 26; all-age and 45+ brackets. Combined 6.25–8.05; neither player above 4.03. Listed fee $42.", id:'liveball', name:'Liveball @ PickleTex', venue:'PickleTex', city:'Georgetown', date:'2026-09-26', end:'2026-09-27', dateLabel:'September 26–27, 2026', day:'26–27', month:'SEP', drive:25, driveLabel:'25–35 min', price:42, priceLabel:"$42–43", dupr:true, rating:false, mixed:true, surface:'Covered outdoor',
    url:'https://app.fluidpb.com/tournaments/liveball-pickletex',
    summary:"Covered courts with men’s, women’s, and mixed 3.5 divisions and a wider rating range.",
    divisions:"Men’s and women’s 3.5 Saturday; mixed 3.5 Sunday. All-age and 45+ brackets verified.",
    format:'Guaranteed four games to 15 or five games to 11.',
    ratings:'Men’s 3.5: combined DUPR 6.25–8.05, with neither player above 4.03. This can be stronger than a strict combined-7.0 bracket.',
    reporting:'All divisions explicitly DUPR-recorded.',
    cost:"Men’s and mixed 3.5 list $42; women’s 3.5 lists $43. The organizer advertises $10 increases after September 8 and again after September 19.",
    deadline:'September 24, 2026.', note:"Women’s and mixed 3.5 permit individual ratings through 4.03. Men’s combined cap is 8.05. Exact start times are due around September 15.",
    deadlineDate:'2026-09-24', deadlineLabel:'Register by Sep 24'},
  {men:true, women:true, mixedDetails:"Mixed 3.5: Saturday afternoon, September 26. Combined 6.10–7.10; neither player above 3.75. Women’s and mixed share the afternoon session—confirm whether both can be played.", womenDetails:"Women’s 3.5: Saturday afternoon, September 26. Combined 6.10–7.10; neither player above 3.75.", menDetails:"Men’s 3.5: Saturday morning, September 26. Combined 6.10–7.10; neither player above 3.75.", id:'nuron', name:'Nuron 1st Anniversary Tournament', venue:'The Picklr Austin Oak Hill', city:'Southwest Austin', date:'2026-09-26', end:'2026-09-26', dateLabel:'September 26, 2026', day:'26', month:'SEP', drive:40, driveLabel:'40–50 min', price:60, priceLabel:'$60–70', dupr:null, rating:true, mixed:true, surface:'Indoor',
    url:'https://app.fluidpb.com/tournaments/nuron-1st-anniversary-tournament',
    summary:"A close rating fit for men’s, women’s, and mixed, at the edge of the drive range.",
    divisions:"Men’s 3.5 in the morning; women’s and mixed 3.5 in the afternoon. Confirm scheduling before entering both afternoon events.",
    format:'Round robin followed by single-elimination playoffs; four games guaranteed.',
    ratings:"All three 3.5 divisions: combined DUPR 6.10–7.10, with neither player above 3.75.",
    reporting:'Result reporting is not stated. Ask the organizer before registering if DUPR reporting is essential.',
    cost:'Registration panel: $60 through September 9, then $70. An additional bracket costs $35.',
    deadline:'The registration panel shows September 24. Descriptive text instead says October 1 and gives September 15 for early bird; confirm with the organizer.',
    note:'Conflicting registration dates in the listing. The 40–50 minute drive is borderline for the preferred range.',
    email:'nuronpb@gmail.com', deadlineDate:'2026-09-24', deadlineLabel:'Sep 24 · confirm date'},
  {men:true, women:true, mixedDetails:"Mixed: Sunday, September 27 at 8 a.m. All-age: combined ≤6.0, neither player above 3.4. Separate 50+ bracket shows individual 2.00–3.80; description says 3.0–3.8, so confirm its lower limit. A 3.5 player does not qualify for the all-age bracket.", womenDetails:"Women’s doubles: Sunday, September 27 at noon. Combined DUPR ≤7.0; neither player above 3.8. Ratings are assessed at registration.", menDetails:"Men’s doubles: Sunday, September 27 at noon. Combined DUPR ≤7.0; neither player above 3.8.", id:'tejas', name:'Everything Pickleball September Classic', venue:'Tejas', city:'Georgetown', date:'2026-09-27', end:'2026-09-27', dateLabel:'September 27, 2026', day:'27', month:'SEP', drive:30, driveLabel:'30–40 min', price:49, priceLabel:'$49', dupr:null, rating:true, mixed:true, surface:'Check venue details',
    url:'https://app.fluidpb.com/tournaments/everything-pickleball-september-classic',
    summary:"A strict combined-7.0 cap for men’s and women’s, with separate mixed options.",
    divisions:"Men’s and women’s at noon; mixed at 8 a.m. on September 27. All-age mixed caps each player at 3.4; a separate 50+ bracket is available.",
    format:'Five games guaranteed; the top four teams advance.',
    ratings:"Men’s and women’s: combined ≤7.0, individual ≤3.8. All-age mixed: combined ≤6.0, individual ≤3.4. Eligibility uses registration-time ratings; later increases do not disqualify.",
    reporting:'Result reporting is not stated. Confirm directly with the organizer.',
    cost:"$49 per player in each listed men’s, women’s, or mixed bracket.", deadline:'September 24, 2026.',
    note:'Great rating fit, pending confirmation that results will be reported to DUPR.',
    email:'mrpickleballrick@aol.com', deadlineDate:'2026-09-24', deadlineLabel:'Register by Sep 24'},
  {men:true, women:true, mixedDetails:"Mixed 3.5+: Sunday, October 4. Uncapped in the supplied listing. Confirm nonresident eligibility.", womenDetails:"Women’s doubles: Saturday, October 3. The organizer confirms the day; the specific women’s skill brackets and caps still need confirmation.", menDetails:"Men’s 3.5+: Saturday, October 3. Uncapped in the supplied listing; confirm field strength.", id:'sun-city', name:'Sun City Fall Brawl', venue:'Sun City · North Courts', city:'Georgetown', date:'2026-10-03', end:'2026-10-04', dateLabel:'October 3–4, 2026', day:'03–04', month:'OCT', drive:30, driveLabel:'30–40 min', price:30, priceLabel:'$30', dupr:true, rating:false, mixed:true, surface:'North Courts',
    url:'https://swishtournaments.com/product/sun-city-fall-brawl/',
    summary:'An affordable weekend option, with open questions about eligibility.',
    divisions:"Men’s and women’s Saturday; mixed Sunday. Men’s and mixed 3.5+ listed; women’s skill brackets need confirmation. North Courts, 700 County Road 245.",
    format:'Set-partner round robin followed by a medal bracket (single elimination).',
    ratings:'3.5+ is uncapped in the supplied listing. Confirm how strong the field will be.',
    reporting:'The registration page explicitly labels the event “DUPR Submitted.”',
    cost:'$30 per player for the first division, plus $20 for a second. The organizer requires registration and payment as a team.',
    deadline:'September 30, 2026.', note:'Confirm whether nonresidents may enter, and the expected level of the uncapped 3.5+ division.',
    deadlineDate:'2026-09-30', deadlineLabel:'Register by Sep 30'},
  {men:true, women:true, mixedDetails:"Mixed 3.5: Sunday, October 25; all-age, 35+, and 50+ brackets. Individual maximum 4.04; all-age and 35+ show a 2.50 minimum. Listed fee $65, plus $30 for an extra event.", womenDetails:"Women’s 3.5: Saturday, October 24; all-age and 50+ brackets. Individual range 2.50–4.04; no combined cap displayed.", menDetails:"Men’s 3.5: Saturday, October 24; all-age and 50+ brackets. Individual range 2.00–4.04; no strict combined-7.0 cap.", id:'apex', name:'002 Dink and Slam Pickleball Jam', venue:'Apex Pickleball Club', city:'Cedar Park', date:'2026-10-24', end:'2026-10-25', dateLabel:'October 24–25, 2026', day:'24–25', month:'OCT', drive:10, driveLabel:'10–15 min', price:65, priceLabel:'$65', dupr:true, rating:false, mixed:true, surface:'501 Cypress Creek Road',
    url:'https://app.fluidpb.com/tournaments/002DSPJ5',
    summary:'The closest major option, with every division reporting to DUPR.',
    divisions:"Men’s and women’s 3.5 Saturday; mixed 3.5 Sunday. All-age and 50+ available; mixed also offers 35+.",
    format:'The relevant divisions use round robin followed by single-elimination playoffs.',
    ratings:"All listed men’s, women’s, and mixed 3.5 brackets permit individual ratings up to 4.04; no strict combined-7.0 cap is displayed.",
    reporting:'Every division is explicitly DUPR-recorded.',
    cost:'$65 for the first event, plus $30 for a second.', deadline:'Registration closes October 19; the refund cutoff is much earlier, September 15.',
    note:"Date conflict: header shows October 25 only; description and division tabs still show October 24–25. Confirm your day. Refund cutoff: September 15. Men’s, women’s, and mixed 3.5 permit individual ratings up to 4.04.",
    deadlineDate:'2026-10-19', deadlineLabel:'Register by Oct 19'},
  {"men": true, "women": true, "mixed": false, "venue": "Tejas Pickleball Club", "city": "Georgetown", "drive": 30, "driveLabel": "30–40 min", "rating": false, "surface": "Check venue details", "id": "baseline-senior", "name": "Baseline Senior Rated Classic", "date": "2026-10-03", "end": "2026-10-03", "dateLabel": "October 3, 2026", "day": "03", "month": "OCT", "price": 45, "priceLabel": "$45", "dupr": null, "url": "https://app.fluidpb.com/tournaments/baseline-senior-rated-classic", "summary": "Senior doubles with separate 50+ and 65+ divisions.", "menDetails": "October 3: 50+ and 65+, each offering ≤3.49 and 3.5+ brackets. Published 3.5+ range extends to 6.00.", "womenDetails": "October 3: 50+ and 65+, each offering ≤3.49 and 3.5+ brackets. Published 3.5+ range extends to 6.00.", "mixedDetails": "No mixed division advertised.", "format": "Round robin, then single elimination.", "ratings": "Age-restricted; current DUPR guides placement, subject to director approval.", "reporting": "DUPR eligibility is enforced; result uploads are not explicitly confirmed.", "cost": "$45 per player.", "deadline": "September 30. Start times are to be finalized after entries close.", "note": "50+ or 65+ eligibility required. The 3.5+ brackets extend well above 3.5. Free cancellation through September 19; $15 fee through September 26, then the full entry fee.", "email": "rick@baselinepickleballusa.com", "deadlineDate": "2026-09-30", "deadlineLabel": "Register by Sep 30"},
  {"men": true, "women": true, "mixed": true, "venue": "Tejas Pickleball Club", "city": "Georgetown", "drive": 30, "driveLabel": "30–40 min", "rating": false, "surface": "Check venue details", "id": "blazing-paddles", "name": "Blazing Paddles Fundraiser · 2nd Annual", "date": "2026-10-10", "end": "2026-10-10", "dateLabel": "October 10, 2026", "day": "10", "month": "OCT", "price": 40, "priceLabel": "$40", "dupr": false, "url": "https://app.fluidpb.com/tournaments/blazing-paddles-pickleball-fundraiser-tournament-2", "summary": "A fundraiser supporting the Round Rock Fire Foundation.", "menDetails": "October 10: intermediate 3.5–4.0, plus beginner and advanced offerings.", "womenDetails": "October 10: intermediate 3.5–4.0 and beginner offerings.", "mixedDetails": "October 10: intermediate 3.5–4.0 and beginner offerings.", "format": "Doubles divisions; match format and game guarantee need confirmation.", "ratings": "Advertised intermediate level is 3.5–4.0; organizer says DUPR ratings are not enforced.", "reporting": "Organizer explicitly states results are not DUPR-recorded.", "cost": "$40 per player.", "deadline": "Registration panel says October 10. Confirm final check-in and division times.", "note": "No DUPR reporting. Refund text gives October 1, 2026 with a $10 fee, while the cancellation panel still shows 2025 dates. Confirm the refund policy.", "email": "Team002@002pickleball.com", "deadlineDate": "2026-10-10", "deadlineLabel": "Oct 10 · confirm time"},
  {"men": true, "women": true, "mixed": true, "venue": "Tejas Pickleball Club", "city": "Georgetown", "drive": 30, "driveLabel": "30–40 min", "rating": false, "surface": "Check venue details", "id": "trey-baring", "name": "Trey Baring Foundation Tournament", "date": "2026-11-07", "end": "2026-11-07", "dateLabel": "November 7, 2026", "day": "07", "month": "NOV", "price": 67, "priceLabel": "$67", "dupr": false, "url": "https://swishtournaments.com/product/trey-baring-foundation-tournament/", "summary": "A charity tournament with 3.5 divisions across all three doubles categories.", "menDetails": "November 7: 3.0, 3.5, and 4.0 advertised. Confirm individual start time.", "womenDetails": "November 7: 3.0, 3.5, and 4.0 advertised. Confirm individual start time.", "mixedDetails": "November 7: 3.0, 3.5, and 4.0 advertised. Confirm individual start time.", "format": "Pool play into single elimination; four games guaranteed.", "ratings": "3.5 divisions advertised; exact eligibility caps are not published.", "reporting": "Foundation website explicitly states DUPR results are not recorded.", "cost": "Swish lists $67 per player for the first division and $60 for a second, paid as a team. Foundation website still advertises $60 per event; verify checkout.", "deadline": "November 2, 2026. Organizer advertises an 8 a.m. event start.", "note": "No DUPR reporting. Refund cutoff is October 7; later withdrawals are treated as donations. Source prices differ.", "email": "treybaringfoundation@gmail.com", "deadlineDate": "2026-11-02", "deadlineLabel": "Register by Nov 2"}
];

const leads = [
  {name:'Saturday Showdown', venue:'Pickleball Kingdom · Pflugerville', date:'September 12, 2026 · confirm listing', tag:'MIXED DOUBLES · NEEDS CONFIRMATION', url:'https://pickleballkingdom.com/clubs/pflugerville/', linkLabel:'Club website',
   text:'The supplied club announcement advertises an intermediate mixed doubles tournament. Exact rating limits, entry fee, and DUPR reporting still need confirmation. The September announcement could not be recovered; this link goes to the club website, not a specific registration page.'},
  {name:'Brushy Creek MUD Pickleball Tournament', venue:'Brushy Creek Community Center · Round Rock', date:'September 12, 2026', tag:'REGISTER BY SEP 10 · RATING DETAILS TO CHECK', url:'https://www.bcmud.org/content/13130/19925/19929/30774.aspx', linkLabel:'Official tournament details',
   text:'The 2026 calendar and linked tournament page confirm September 12, with registration closing September 10. Men’s, women’s, and mixed recreational, competitive, and 50+ doubles are listed. Open to nonmembers; doubles fees list $20 members, $25 residents, $35 nonresidents—confirm whether charged per player or team. Numerical rating limits and DUPR reporting remain unconfirmed.'}
];

const teamEvents = [
  {id:'ranchers-mlp', group:'local', name:'Texas Ranchers Fall Round Up', date:'September 12–13, 2026', end:'2026-09-13', venue:'The Picklr Round Rock · Round Rock', status:'Availability unconfirmed',
    format:'MLP-style mixed team competition. Four-player team; men’s, women’s, and mixed doubles matches.',
    ratings:'The supplied research lists DUPR-14 at 8 a.m. September 12, with a four-player combined cap of 14.9. Confirm individual limits and team composition.',
    cost:'$75 per player in the supplied listing ($300 for four players). Registration deadline unconfirmed.',
    reporting:'DUPR reporting unconfirmed.',
    note:'Previously listed as full in all-age DUPR-14. The event appears in indexed results but was absent from the live directory. Confirm event status, venue, and availability before planning a team.',
    url:'https://app.fluidpb.com/', linkLabel:'Check Fluid PB directory'},
  {id:'jomg-mlp', group:'local', name:'JOMG Pickleball Club Championship', date:'September 19–20, 2026 · confirm division day', end:'2026-09-20', venue:'Apex · Cedar Park · approx. 10–15 min', status:'Club entry required',
    format:'MLP-style club competition: four starters plus two substitutes. Both Open and 50+ age categories are advertised.',
    ratings:'DUPR 12, 14, 16, 18, and 20 divisions. Ask the organizer for exact aggregate and individual caps; the division name alone is not the cap.',
    cost:'$95 per main-roster player; $25 per substitute. Four starters total $380, or $430 with two substitutes. Deadline not published.',
    reporting:'DUPR reporting unconfirmed.',
    note:'Players must have been club members for at least 60 days. Club-entry only: ask your club for selection. The site lists September 19–20; the earlier Apex announcement singled out September 19 for adults. Confirm your division’s day.',
    url:'https://pcc.jomgpickleball.com/', linkLabel:'View championship details', email:'info@jomgpickleball.com'},
  {id:'newcombe-milp', group:'travel', name:'The Dink MiLP @ John Newcombe Country Club', date:'September 19–20, 2026', end:'2026-09-20', venue:'625 Mission Valley Road · New Braunfels', status:'Longer drive · official MiLP',
    format:'Four-player mixed teams. Women’s doubles, men’s doubles, and two mixed games; a 2–2 tie triggers a Dreambreaker. Round robin into playoffs; at least three team matches.',
    ratings:'Published DUPR-14 cap: 14.300 combined, 4.100 maximum per player. Confirm the offered bracket and play day. Each player’s rating locks after joining, signing, and paying.',
    cost:'$80 per player ($320 for four), plus required active DUPR+ membership.',
    reporting:'Listing explicitly identifies a DUPR-verified event.',
    note:'Outside the original local drive range; check navigation. The page displays a September 13, 2027 registration deadline despite the 2026 event—confirm the real deadline. Listed refund cutoff was August 19, 2026 ($25 withdrawal fee). Outdoor venue.',
    url:'https://pickleballtournaments.com/tournaments/the-dink-minor-league-pickleball-at-john-newcombe-country-club-texas', linkLabel:'View MiLP registration'},
  {id:'cranky-v3', group:'travel', name:'The Dink MiLP v3 @ Cranky Pickle', date:'September 26–27, 2026', end:'2026-09-27', venue:'624 Krueger Canyon · New Braunfels', status:'Longer drive · three-player v3',
    format:'Three-player gendered teams: three games to 21 per match, round robin into playoffs. The listing advertises at least three matches and six played games.',
    ratings:'DUPR-11 permits 11.300 combined, with no player above 4.100. Published alternatives: DUPR-9 (9.300 / 3.600 individual), DUPR-13 (13.300 / 4.600), and DUPR-15 (15.300 / no individual maximum). Confirm bracket availability and day.',
    cost:'$60 per player ($180 for three), plus required active DUPR+ membership. Registration closes September 19, 2026.',
    reporting:'Listing explicitly identifies a DUPR-verified event.',
    note:'Outside the original local drive range. The page mixes generic four-player text with v3 rules; confirm your format. Its August 26 refund cutoff ($25 withdrawal fee) and outdoor policy contain “VERIFY LANGUAGE” placeholders—confirm both.',
    url:'https://pickleballtournaments.com/tournaments/the-dink-milp-v3-at-cranky-pickle-new-braunfels-texas', linkLabel:'View v3 registration'},
  {id:'pickleland-mlp', group:'recurring', name:'Pickleland Saturday MLP-style events', date:'Recurring Saturdays · check individual dates', venue:'Pickleland · Pflugerville', status:'Weekly offering · dates unverified',
    format:'Team play with men’s, women’s, and mixed doubles, plus a Dreambreaker tiebreak. Confirm roster requirements in the individual booking.',
    ratings:'The club offers skill-based divisions including 3.5. Exact team caps vary by listing and are not confirmed for future Saturdays.',
    cost:'Weekly mini-tournaments are free for Unlimited members; guests pay a drop-in fee. Check the individual booking for price and deadline.',
    reporting:'Most club events report to DUPR, but some weekly mini-tournaments do not. Confirm the particular Saturday event.',
    note:'Recurring program, not a verified calendar of individual tournaments through January 7. Check the booking before assembling a team.',
    url:'https://pickleland.com/tournaments', linkLabel:'View weekly tournament details', booking:'https://play.pickleland.com/programs'}
];
